image: gitlab.protontech.ch:4567/protonvpn/android/android-app-new:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle
    - '**/build'
    - '**/**/build'
    - '**/**/**/build'

stages:
  - analyze
  - build
  - test
  - publish
  - commit
  - slackRelease

#####################
detekt analysis:
  stage: analyze
  tags:
    - medium
  script:
    - ./gradlew multiModuleDetekt
  artifacts:
    expire_in: 1 month
    reports:
      codequality: config/detekt/reports/mergedReport.json

assemble:
  stage: build
  tags:
    - large
  script:
    - ./gradlew assemble
  # artifacts:
  #   paths:
  #   - app/build/outputs/

debugTests:
  stage: test
  tags:
    - medium
  script:
    - ./gradlew -Pci --console=plain allTest

include:
  - project: 'agarroux/publish-github'
    file: '/jobs/release.gitlab-ci.yml'

release-publish-github:
  stage: publish
  tags:
    - small
  only:
    - master
  variables:
    RELEASE_SYNC_PUBLIC_URL: git@github.com:ProtonMail/protoncore_android.git
    RELEASE_SYNC_TO_BRANCH: 'master'
    RELEASE_SYNC_FROM_BRANCH: 'master'
  extends: .release-sync-commit-shared

publishMaven:
  stage: publish
  tags:
    - large
  script:
    - ./gradlew publishNewRelease --no-daemon --no-parallel
  only:
    - master
  artifacts:
      expire_in: 10 days
      paths:
          - new_releases.tmp
          - releases
          - docs
          - README.md

publishGradlePortal:
  stage: publish
  tags:
    - small
  script:
    - ./gradlew -p util/gradle assemble && ./gradlew -p util/gradle publishAll
  only:
    - master
  artifacts:
    expire_in: 10 days
    paths:
      - new_releases.tmp
      - releases
      - docs
      - README.md

commitRelease:
  stage: commit
  tags:
    - small
  needs:
      - job: publishMaven
        artifacts: true
  script:
    - ./util/commitRelease
  only:
    - master

postReleaseToSlack:
  stage: slackRelease
  tags:
    - small
  needs:
      - job: publishMaven
        artifacts: true
  script:
    - ./util/postReleaseToSlack
  only:
    - master
