[versions]
easyGradle = "2.8"
kotlin = "1.5.31"

[plugins]
easyGradle = { id = "studio.forface.easygradle", version.ref="easyGradle" }
kotlinx-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version ="0.8.0" }
kotlinGradle = { id = "org.jetbrains.kotlin.jvm", version.ref="kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin" }

[libraries]
android-pluginGradle = "com.android.tools.build:gradle:7.0.4"

vanniktech-pluginGradleMavenPublish = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"

publish-pluginGradle = "io.github.gradle-nexus:publish-plugin:1.1.0"

dokka-pluginGradle = "org.jetbrains.dokka:dokka-gradle-plugin:1.5.30"

easyGradle-dsl = { module = "studio.forface.easygradle:dsl", version.ref = "easyGradle" }
easyGradle-androidDsl = { module = "studio.forface.easygradle:dsl-android", version.ref = "easyGradle" }

kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1"
