[versions]
easyGradle = "2.8"

[plugins]
easyGradle = { id = "studio.forface.easygradle", version.ref="easyGradle" }

[libraries]
android-pluginGradle = "com.android.tools.build:gradle:7.0.2"
easyGradle-dsl = { module = "studio.forface.easygradle:dsl", version.ref = "easyGradle" }
easyGradle-androidDsl = { module = "studio.forface.easygradle:dsl-android", version.ref = "easyGradle" }
