[versions]
androidGradle = "7.0.4"
arturboschDetektGradle = "1.17.1"
benManesVersions = "0.39.0"
daggerHiltAndroid = "2.38.1"
easyGradle = "2.8"
kotlin = "1.5.31"
kotlinSerialization = "1.3.1"
kotlinBinaryCompatibilityValidator = "0.8.0"
vanniktechPublish = "0.18.0"
gradleNexusPublish = "1.1.0"

[plugins]
benManes-versions-gradle = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
easyGradle = { id = "studio.forface.easygradle", version.ref = "easyGradle" }
kotlin-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibilityValidator" }
kotlin-gradle = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
arturbosch-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "arturboschDetektGradle" }
dagger-hilt-android-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "daggerHiltAndroid" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin" }
easyGradle-dsl = { module = "studio.forface.easygradle:dsl", version.ref = "easyGradle" }
easyGradle-androidDsl = { module = "studio.forface.easygradle:dsl-android", version.ref = "easyGradle" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
gradleNexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "gradleNexusPublish" }
vanniktech-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktechPublish" }
