image: ${CI_REGISTRY}/android/shared/docker-android:new-ci-runners-k8s-snapshot

stages:
  - firebase

.firebase-tests-common:
  stage: firebase
  variables:
    RESULTS_DIR: "${CI_COMMIT_REF_NAME}/${CI_COMMIT_SHORT_SHA}/${CI_JOB_NAME}"
  tags:
    - medium
  script:
    - gcloud config set project $CLOUD_PROJECT_ID_CORE
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT
    - gcloud firebase test android run
      --app coreexample/build/outputs/apk/localProperties/debug/coreexample-localProperties-debug.apk
      --test coreexample/build/outputs/apk/androidTest/localProperties/debug/coreexample-localProperties-debug-androidTest.apk
      --device model=Pixel2,version=28
      --test-targets "$TEST_TARGET"
      --timeout 25m
      --results-dir=$RESULTS_DIR
  after_script:
    - mkdir -p screenshots
    - mkdir -p logs
    - gsutil cp $FIREBASE_BUCKET_URL/$RESULTS_DIR/Pixel2-28-en-portrait/logcat logcat.txt
    - gsutil cp $FIREBASE_BUCKET_URL/$RESULTS_DIR/Pixel2-28-en-portrait/video.mp4 video.mp4
    - gsutil cp $FIREBASE_BUCKET_URL/$RESULTS_DIR/Pixel2-28-en-portrait/test_result_1.xml test_result_1.xml
    - gsutil -m cp -r $FIREBASE_BUCKET_URL/$RESULTS_DIR/Pixel2-28-en-portrait/test_cases ./logs
    - gsutil -m cp -r $FIREBASE_BUCKET_URL/$RESULTS_DIR/Pixel2-28-en-portrait/artifacts/sdcard/screenshots ./screenshots 2> /dev/null || true
    - python3 coreexample/ci/process_report.py test_result_1.xml test_result.xml
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: assemble
      artifacts: true
  artifacts:
    when: always
    reports:
      junit: test_result.xml
    paths:
      - screenshots
      - logcat.txt
      - video.mp4
      - logs

uitest:signup:
  variables:
    TEST_TARGET: "package me.proton.core.test.android.uitests.tests.medium.auth.signup"
  extends: .firebase-tests-common

uitest:login:
  variables:
    TEST_TARGET: "package me.proton.core.test.android.uitests.tests.medium.auth.login"
  extends: .firebase-tests-common

uitest:payments:
  variables:
    TEST_TARGET: "package me.proton.core.test.android.uitests.tests.medium.payments"
  extends: .firebase-tests-common

uitest:plans:
  variables:
    TEST_TARGET: "package me.proton.core.test.android.uitests.tests.medium.plans"
  extends: .firebase-tests-common

uitest:usersettings:
  variables:
    TEST_TARGET: "package me.proton.core.test.android.uitests.tests.medium.usersettings"
  extends: .firebase-tests-common
