image: ${CI_REGISTRY}/android/shared/docker-android:v1.0.0-alpha09

stages:
  - firebase

.firebase-tests-common:
  stage: firebase
  tags:
    - medium
  script:
    - gcloud config set project $CLOUD_PROJECT_ID_CORE
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT
    - gcloud firebase test android run
      --app coreexample/build/outputs/apk/localProperties/debug/coreexample-localProperties-debug.apk
      --test coreexample/build/outputs/apk/androidTest/localProperties/debug/coreexample-localProperties-debug-androidTest.apk
      --device model=Pixel2,version=28
      --test-targets "$TEST_TARGET"
      --timeout 25m
      --num-flaky-test-attempts=2
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: assemble
      artifacts: true

uitest:signup:
  before_script:
    - TEST_TARGET="package me.proton.core.test.android.uitests.tests.medium.auth.signup"
  extends: .firebase-tests-common

uitest:login:
  before_script:
    - TEST_TARGET="package me.proton.core.test.android.uitests.tests.medium.auth.login"
  extends: .firebase-tests-common

uitest:payments:
  before_script:
    - TEST_TARGET="package me.proton.core.test.android.uitests.tests.medium.payments"
  extends: .firebase-tests-common

uitest:plans:
  before_script:
    - TEST_TARGET="package me.proton.core.test.android.uitests.tests.medium.plans"
  extends: .firebase-tests-common

uitest:usersettings:
  before_script:
    - TEST_TARGET="package me.proton.core.test.android.uitests.tests.medium.usersettings"
  extends: .firebase-tests-common