.gradle-cache:
  cache:
    - key:
        prefix: global-gradle-cache
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - ${GRADLE_USER_HOME}/wrapper
        - ${GRADLE_USER_HOME}/caches
        - ${GRADLE_USER_HOME}/notifications
      policy: pull-push

    - key: branch-build-cache-${CI_COMMIT_REF_SLUG}
      paths:
        - ./**/build
      policy: pull-push

.ruby-cache:
  cache:
    - key:
        prefix: ruby-cache
        files:
          - Gemfile.lock
      paths:
        - ${BUNDLE_GEM_PATH}
      policy: pull-push
